# === ПУТИ К ФАЙЛАМ MORROWIND ===
morrowind_data_files_dir: "F:/Games/MorrowindFullrest/game/Data Files"

# === ЯЗЫК СИСТЕМЫ ===
language: "ru"

# === ЛОГИРОВАНИЕ ===
log:
  level: "INFO"
  file_path: "logs/ai_server.log"

# === РАСПОЗНАВАНИЕ РЕЧИ (STT) ===
speech_to_text:
  backend: "vosk"  # vosk, whisper, azure
  vosk:
    model_path: "vosk-model-small-ru-0.22"
    sample_rate: 16000
  whisper:
    model: "base"
    language: "ru"
  azure:
    key: ""
    region: ""

# === СИНТЕЗ РЕЧИ (TTS) ===
text_to_speech:
  backend: "elevenlabs"  # elevenlabs, azure
  elevenlabs:
    api_key: ""
    voice_id: ""
  azure:
    key: ""
    region: ""

# === LLM ПРОВАЙДЕРЫ ===
llm:
  system:
    google:
      api_key: "ТВОЙ_GEMINI_API_КЛЮЧ_ЗДЕСЬ"
      model: "gemini-1.5-flash"
    anthropic:
      api_key: ""
      model: "claude-3-haiku-20240307"
    openai:
      api_key: ""
      model: "gpt-3.5-turbo"
    mistral:
      api_key: ""
      model: "mistral-small-latest"

# === ШИНА СОБЫТИЙ ===
event_bus:
  host: "127.0.0.1"
  port: 9090

# === RPC СЕРВЕР ===
rpc:
  host: "127.0.0.1"
  port: 18080

# === БАЗА ДАННЫХ ===
database:
  path: "data/main.db"

# === БАЗА ДАННЫХ ИГРОКА ===
player_database:
  path: "data/players.db"

# === БАЗА ДАННЫХ НПС ===
npc_database:
  path: "data/npcs.db"

# === РЕЖИССЁР НПС ===
npc_director:
  max_concurrent_conversations: 5
  response_timeout: 30

# === ГОЛОС НПС ===
npc_speaker:
  default_voice: "alloy"
  speech_rate: 1.0

# === ИНСТРУКЦИИ СЦЕНЫ ===
scene_instructions:
  enable_voice_commands: true
  hotkey_voice: "alt"

# === HTTP МОСТ (твои настройки) ===
http_bridge:
  host: "127.0.0.1"
  port: 8080

ai_server:
  host: "127.0.0.1"
  port: 18080
  base_url: "http://127.0.0.1:18080"

logging:
  level: INFO
