# === ПУТЬ К ДАННЫМ MORROWIND ===
morrowind_data_files_dir: "F:/Games/MorrowindFullrest/game/Data Files"

# === ЯЗЫК ===
language: "ru"

# === НАСТРОЙКИ ЛОГИРОВАНИЯ ===
log:
  level: "INFO"
  file_path: "logs/ai_server.log"
  log_to_console: true
  log_to_console_level: "INFO"
  log_to_file: true
  log_to_file_level: "DEBUG"

# === РАСПОЗНАВАНИЕ РЕЧИ (STT) ===
speech_to_text:
  backend: "vosk"
  system: "pynput"
  delayed_stop_sec: 0.5
  vosk:
    model_path: "vosk-model-small-ru-0.22"
    sample_rate: 16000
  whisper:
    model: "base"
    language: "ru"
  azure:
    key: ""
    region: ""

# === СИНТЕЗ РЕЧИ (TTS) ===
text_to_speech:
  backend: "elevenlabs"
  system: "pygame"
  output: "device"
  elevenlabs:
    api_key: ""
    voice_id: ""
  azure:
    key: ""
    region: ""

# === LLM ПРОВАЙДЕРЫ ===
llm:
  system:
    type: "google"
    google:
      api_key: "ТВОЙ_GEMINI_API_КЛЮЧ_ЗДЕСЬ"
      model: "gemini-1.5-flash"
    anthropic:
      api_key: ""
      model: "claude-3-haiku-20240307"
    openai:
      api_key: ""
      model: "gpt-3.5-turbo"
    mistral:
      api_key: ""
      model: "mistral-small-latest"

# === ШИНА СОБЫТИЙ ===
event_bus:
  host: "127.0.0.1"
  port: 9090
  system: "mqtt"
  producers: []
  consumers: []

# === RPC СЕРВЕР ===
rpc:
  host: "127.0.0.1"
  port: 18080
  max_wait_time_sec: 30

# === БАЗА ДАННЫХ ===
database:
  path: "data/main.db"
  directory: "data"

# === БАЗА ДАННЫХ ИГРОКА ===
player_database:
  path: "data/players.db"
  max_stored_story_items: 100
  max_shown_story_items: 20
  book_name: "Дневник приключений"

# === БАЗА ДАННЫХ НПС ===
npc_database:
  path: "data/npcs.db"
  max_stored_story_items: 50
  max_used_in_llm_story_items: 10

# === РЕЖИССЁР НПС ===
npc_director:
  max_concurrent_conversations: 3
  response_timeout: 30
  npc_max_phrases_after_player_hard_limit: 5
  random_comment_proba: 0.1
  random_comment_delay_sec: 30
  strategy_random: false

# === ГОЛОС НПС ===
npc_speaker:
  default_voice: "alloy"
  speech_rate: 1.0

# === ИНСТРУКЦИИ СЦЕНЫ ===
scene_instructions:
  enable_voice_commands: true
  hotkey_voice: "alt"
  file: "data/scene_instructions.txt"

# === HTTP МОСТ (твои настройки сохранены) ===
http_bridge:
  host: "127.0.0.1"
  port: 8080

ai_server:
  host: "127.0.0.1"
  port: 18080
  base_url: "http://127.0.0.1:18080"

logging:
  level: INFO
